version: 0.2

phases:
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region $SOURCE_REGION --registry-ids $SOURCE_ACCOUNT_ID)
      - echo "Pulling source image from $SOURCE_IMAGE"
      - docker pull $SOURCE_IMAGE
      - docker tag $SOURCE_IMAGE $DESTINATION_IMAGE
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $DESTINATION_REGION --registry-ids $DESTINATION_ACCOUNT_ID)
      - echo "Pushing to destination $DESTINATION_IMAGE"
      - docker push $DESTINATION_IMAGE
