version: 0.2

phases:

  build:
    commands:
      - $(aws ecr get-login --no-include-email --region $SOURCE_REGION --registry-ids $SOURCE_ACCOUNT_ID)
      - echo "Pulling source image from $SOURCE_IMAGE"
      - docker pull --all-tags $SOURCE_REPOSITORY
      - docker images $SOURCE_REPOSITORY --format "docker tag {{.Repository}}:{{.Tag}} $DESTINATION_REPOSITORY:{{.Tag}}" | bash

  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $DESTINATION_REGION --registry-ids $DESTINATION_ACCOUNT_ID)
      - echo "Pushing to destination $DESTINATION_REPOSITORY"
      - docker push $DESTINATION_REPOSITORY

